let adjective="beautiful";
let noun="dog";
let verb="smile";
let place="forest";
let adjective2="big";
let noun2="chilli pepper";
let firstStory="Once upon a time, there was a(n) "+adjective+" "+noun+" who loved to eat "+noun2+". "+"The "+noun+" lived in a "+place+" and had "+adjective2+" nostrils that blew fire when it was "+verb+".";
console.log("First story: "+firstStory);
adjective="kind";
noun="cat";
verb="sleep";
place="house";
adjective2="small";
noun2="strawberry";
let secondStory="Once upon a time, there was a(n) "+adjective+" "+noun+" who loved to eat "+noun2+". "+"The "+noun+" lived in a "+place+" and had "+adjective2+" nostrils that blew fire when it was "+verb+".";
console.log("Second story: "+secondStory);
